bugfix: Show episodes filtering
molnar-a/lahmacun-app pull request #3
Opened 2022-02-06 21:08 UTC by molnar-a

2022-02-17 06:43 UTC, baxgas requested changes
Doesn't work, please check the date comparison 

`new Date()` gives back the date with time, and you need only the date, in the same format as `play_date` from arcsi

<img width="406" alt="image" src="https://user-images.githubusercontent.com/36408851/154419863-4168cd50-3283-42ec-9950-f89f4c3c3e44.png">

2022-02-17 06:43 UTC, baxgas commented on src/components/ShowDetail/showDetail.tsx
> +      return item.archived && playDate < new Date();
@molnar-a sorry, but this doesn't work, you are comparing different types of Date formats.
The copy/paste fix from ananasz would be 
```
const availableItems = items.filter(item => {
      const d = new Date();
      const year = d.getFullYear();
      const month = (d.getMonth() + 1).toLocaleString('en-US', {
        minimumIntegerDigits: 2
      });
      const day = d
        .getDate()
        .toLocaleString('en-US', { minimumIntegerDigits: 2 });
      const today = `${year}-${month}-${day}`;
      return item.archived && item.play_date < today;
    });
```
(but of course this `today` to arcsi-style formatting snippet could be modularized)

2022-02-21 21:14 UTC, molnar-a commented on src/components/ShowDetail/showDetail.tsx
> +      return item.archived && playDate < new Date();
Thanks! I've resolved this now

2022-02-22 11:12 UTC, baxgas approved these changes

2022-02-22 11:14 UTC, baxgas commented
@molnar-a Yesss! Seems it is working perfectly – tried on devarcsi which has some episodes made for this eg.
```
{
        "number": 789,
        "name": "future episode 789",
        "description": "big beats so good",
        "play_date": "2025-04-05",
        "id": 766,
        "download_count": 0,
        "image_url": "789/learning_audio_classification_with_torso-future_episode_789.jpg",
        "archived": false,
        "play_file_name": null
      },
```
in Learning Audio...
Was filtered out nicely. Merge the branch please and it can go in app stores

2022-02-22 12:22 UTC, merged